### PR TITLE
Higher or lower

### PR DESCRIPTION
**Pull request by rrees**
A simple solitaire game or classic gameshow staple depending on your vintage.

This is a card game like the 21s problem but starts off with a much simpler situation and then asks the implementation to be increasing parametrised which should reward good initial approaches.

I thought this was too simple but I've seen people struggling with the game loop in a way I hadn't expected.

### CODE REVIEW

**Comment by jennysivapalan** [comment]
Thanks @rrees, agreed it sounds simple but I haven't tried it. I'll see if we can get a few volunteers to try this (and https://github.com/guardian/pairing-tests/pull/26) as pairs and work out if it's suitable or needs a few tweaks.

**Comment by jennysivapalan** [comment]
@rrees - @nicl and I tried it last week. We found we were able to complete it quite quickly.  We will have a think too but we were wondering if you had any suggestions to make the the extensions more challenging? I can email over the gist of our attempt, let me know if you would like it.

**Comment by rrees** [comment]
The gist would be handy. I've done this with mostly inexperienced programmers so I haven't seen anyone complete it yet! How much time did you have left when you finished it?

**Comment by jennysivapalan** [comment]
@rrees Sent you an email of the gist. It took us ~30 minutes, but given your experience we may have mis-read the notes. Let me know and we can also try and get a couple of other people to try it.

**Comment by rrees** [comment]
I've put comments on the Gist. Your solution is pretty solid but as per the gist I wonder what more you would want to see if someone provided the code you created.

**Pull request closed without merging**
